### ISSUE TITLE
Propogate errors to callback

### ISSUE THREAD

**Issue by laike9m** [s1ntoneli/AppUpdater#3]
Currently, the error information is hidden in the stack and not propogated to user callbacks.

I can work on this one.

**Comment by s1ntoneli** [comment]
I have checked the example, and apart from the successful installation callback (which is explained in the readme), the other callbacks are working properly.

Which specific issue are you referring to, and how did you reproduce it? 

If you can resolve it, please feel free to submit a pull request.

**Comment by s1ntoneli** [comment]
should resolved here:

fix issue that waitUntilExit hang when unzipping file:
https://github.com/s1ntoneli/AppUpdater/commit/11c71336f56462bcc793b6ff23d51b369de9b55a

the root cause is that cause the unzipping task fills the output pipe then the process hanged, effectively blocking waitUntilExit from returning.

**Comment by s1ntoneli** [comment]
upgrade to 0.1.5 to avoid hanging
